# Confirmatory Factor Analysis

## Research scenario

A team of developmental psychologists (Michelle, Lucas, and Alexis) is interested in constructing a psychometric theory on being manipulative to others. Our substantive theory suggests that sensation seeking (`senseek`), Machiavellianism (`totmach`), powerlessness (`totpower`), social monitoring (`totsms`), and faith (`totfaith`) measure the one underlying latent construct: being manipulative. We are thus to conduct a confirmatory factor analysis that measures manipulativeness by the five measures. Use the `mmpi.csv` dataset.

## Main questions

1. Draw a path diagram.

2. Write Mplus syntax.

```{r, eval=FALSE}
! Annotate what you are doing in this line
title: Confirmatory factor analysis

data:
! Annotate what you are doing in this line
file is mmpi.csv;

variable:
! Annotate what you are doing in this line
names are subid source age sex race slpneed slpget anxiety depress
hostile posafect senseek totaccpt totsavoid totici tottrust totmach
totpower totsms aggress impulse harm epixtra epineuro totrathus
totfaith totcyc totsd tothypo avoid distress;

! Annotate what you are doing in this line
usevariables are senseek totmach totpower totsms totfaith;

analysis:
! Annotate what you are doing in this line
estimator = ML;

model:
! Annotate what you are doing in this line
manipulativeness BY senseek totmach totpower totsms totfaith;

! In case you want to free the first factor loading
! and instead scale the variance of the factor
! manipulativeness BY senseek* totmach totpower totsms totfaith;
! manipulativeness@1;

output:
! Annotate what you are doing in this line
TECH1;

! Annotate what you are doing in this line
stdyx;
```

3. Run the analysis and interpret the results.

## Bonus questions

1. By default, Mplus fixes the first factor loading to 1 for model identification. What if we want to free the first factor loading and instead scale the variance of the factor?

2. Calculate the degrees of freedom by hand. Compare your result with that of Mplus.

